### ISSUE TITLE
[JOSS review] Installation from source requires pre-installed Django

### ISSUE THREAD

**Issue by ixjlyons** [callat-qcd/espressodb#41]
Minor issue. The README currently lists the following steps to install EspressoDB from source for testing:

> To run the tests, clone this repo, install the dependencies

```bash
pip install .
pip install -r requirements-dev.txt
pip install -r example/my_project/requirements.txt
```

The first step fails in a clean environment because `espressodb/__init__.py` imports Django. It may also be worth noting that installing the sdist from PyPI also fails for the same reason:

```bash
pip install --no-binary espressodb espressodb
```

I see the latter as pretty much a non-issue though since you're providing a universal wheel. I think the simplest solution would be to re-order the steps so the requirements are installed first. Perhaps there's a way to defer importing Django for settings -- I'm not sure.

https://github.com/openjournals/joss-reviews/issues/2007

**Comment by ckoerber** [comment]
Hello @ixjlyons,

Thank you for pointing out this issue.

The easiest fix would indeed be updating the docs to run the `requirements` install before the `espressodb` install. 

I believe it should be possible to place the `espressodb/__init__.py` Django import in the provided `init` function. This would delay the import until `init()` is actually called and thus allows to run a `no-binary` install. I have to run some checks&mdash;if this works out and does not affect other functionalities, I will include the delayed import in the next version.

**Comment by ckoerber** [comment]
The commit 9df504e should resolve this issue (no doc update needed). This should also allow the `no-binary` install which will be tested once the new version is ready for shipping.

**Comment by ckoerber** [comment]
The no binary install now works with v1.1.0.

Thank you for your feedback @ixjlyons.
