### ISSUE TITLE
Can not delete row with ManyToMany

### ISSUE THREAD

**Issue by cchang5** [callat-qcd/espressodb#56]
The website does not support deleting a row that has a ManyToMany column.
Currently need to delete the through table with SQL before the rows can be deleted.

**Comment by ckoerber** [comment]
What is the desired behavior? The default behavior might be ambiguous: do you want to 

1. delete all entries in the through table connected to the row 
2. delete all remote table entries connected to this row as well  

I am currently not sure whether or not this is an issue concerning EspressoDB (the admin m2m columns do not have expected features) or an issue regarding the table implementation (no `on_delete` like behavior is implemented). Can you point me to the table implementation?

PS: You can also run Python to [clear the through table](https://docs.djangoproject.com/en/3.0/topics/db/examples/many_to_many/):
```python
row.m2m_column.clear()
```
