### ISSUE TITLE
BinaryField doesn't show up in populate

### ISSUE THREAD

**Issue by cchang5** [callat-qcd/espressodb#59]
I think maybe columns that do not show up in the Admin page does not show up the in populate page?
We're trying to save gv.dump() to a binary type.

**Comment by ckoerber** [comment]
Hey, thanks for pointing this out.

This might be related to #60. Is it the string of instances which does not show the field. If so, this might be fixed soon. 

If this is not what you are asking:  [`get_open_fields`](https://github.com/callat-qcd/espressodb/blob/b4654407ce7e201802b030086d268b48db9d1d94/espressodb/base/models.py#L167) decides which columns are detectable. E.g., if it is not `id`, `user`, not editable or  a pointer field, it should be present.

If that's the case, can you point me to your implementation or provide a minimal example?
